---
- name: add nsqadmin user
  user: name={{ nsq_nsqadmin_user }}

- name: nsqadmin upstart service
  template: src=etc/init/nsqadmin.conf.j2 dest=/etc/init/nsqadmin.conf
  notify:
    - restart nsqadmin
